language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - docker pull selenium/node-firefox
  - docker run -d -p 127.0.0.1:4444:4444 selenium/node-firefox
  - docker run -d -p 127.0.0.1:8080:8080 -e CATALINA_OPTS="-DSSO_SERVERS=127.0.0.1" opencadc/storage
  - docker ps -a
  - gradle -DintTest_web_app_url=http://127.0.0.1:8080 intTestFirefox -Dproject.intTest_selenium_server_url=http://127.0.0.1:4444

script: gradle clean dockerize

after_success:
  - docker push opencadc/storage