language: java
jdk:
- oraclejdk8
sudo: required
script: gradle -PkeystorePassword=$storepass clean build
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_1096bbb7f264_key -iv $encrypted_1096bbb7f264_iv
  -in cadcKeystore.enc -out cadcKeystore -d
- docker pull selenium/node-firefox
- docker pull selenium/node-chrome
env:
  global:
    secure: RLN+OYh3WRZGvFoehhc7QIngSiokaP4CD+v4g18H8Zokr+swtTIcF+o9M6QFLq/0yac+YShdsOsJltm8lIoTmrs20yo19DJOXn/6xvRjqI7a12EWYpKnd2XqNIYJ7kDTrr3gPdKD+50ubJqwG4e9u8La2OSj2/3nemPUrsPsTEwqQ4s2Uh4uVU8toGFQ/1MNW2TcQoMZq/S9+mqRUlFUfS6mEBHiSA1u+452hMmuu9sq1g0H5bxdnmOppPvOlX3vPDTaEQ1xzX26B0vgYVD7/2ITt14O7P6LjVDeXE7D8BDZmmDtLd3LOxaEL2+H9AWKa6m7pGnv6w3RTLA3Nb07eZe+6lhRJxB2FNxOn7+K1XP3vUbFugsZX8hR/qtDZgcBGCuZVapm4SyMGD9VJoC8vgll4WJ1591JvPKtZkYigeutO3y9nuLPP3wJUwpgI5aT7TmO/39O9/bWzrij2AiMfR854o/xZM9JDvDiMAvHcO2sCGYIdwbXLYU2PpJbiYBWF6ghgE5R/w/mvyIS7TT1o8WMKn/9PzcQmM5aYPAsbNWj1PYZwewoe1Lmzk+dkkNPUoYwIFvQPIkRAWsoBukYHnIGAEGMknkuZExUFnJTivipzyvufR8WTIXaSF52fIDagseOtwPEZ638on42X9e1d13MT49Ldug6Eh0lU8ElfF4=
