language: java

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - docker pull selenium/node-firefox
  - docker run -d --net=host -p 4444:4444 selenium/node-firefox
  - docker run -d --net=host -p 8080:8080 -e CATALINA_OPTS="-DSSO_SERVERS=127.0.0.1 apps.canfar.net www.canfar.phys.uvic.ca" opencadc/storage
  - docker ps -a
  - gradle -i -PintTest_selenium_server_url=http://127.0.0.1:4444 -PintTest_web_app_url=http://127.0.0.1:8080 intTestFirefox

script: gradle clean dockerize

after_success:
  - docker push opencadc/storage