version: '2'
services:
  storage-ui:
    image: opencadc/storage
    ports:
      - '8080:8080'
    environment:
      - CATALINA_OPTS="-DSSO_SERVERS=jenkinsd.cadc.dao.nrc.ca apps.canfar.net www.canfar.phys.uvic.ca"
