version: '3.2'
services:
  selenium-firefox:
    image: selenium/standalone-firefox:3
    ports:
      - '4444:4444'
    networks:
      - 'selenium'
  storage.canfar.net:
    image: opencadc/storage:SNAPSHOT
    build: ./
    ports:
      - '8080:8080'
      - '5555:5555'
    networks:
      - 'selenium'
    depends_on:
      - 'selenium-firefox'
    environment:
      CATALINA_OPTS: -DSSO_SERVERS="www.canfar.net www.canfar.phys.uvic.ca"

networks:
  selenium:
